### ISSUE TITLE
PopDel not compatible out of the box with hg37d5

### ISSUE THREAD

**Issue by holtgrewe** [kehrlab/PopDel#1]
The code in the following location appears to assume hg38...

https://github.com/kehrlab/PopDel/blob/0cf86a56b87abcde512d0625adef582a6c4a9d56/utils_popdel.h#L827

I can work around this with the given `-i` hint. hg37d5 support out of the box would be nice.

**Comment by holtgrewe** [comment]
Also, it's not clear to me how the sample intervals were selected...

**Comment by holtgrewe** [comment]
OK, I see now that it's in the readme. But selecting them appears to be a bit tedious... Also, when looking at this in UCSC, it's hard to compare mapabilities (Duke unique not available for hg38 and vice versa for Bismap...).

I'd appreciate guidance whether just using the same intervals for hg19 should just work...

**Comment by serosko** [comment]
Thank you for your suggestions.
Adding build-in regions for GRCh37/hg19 sounds like a sensible addition and will be done, same goes for the requested guidance in the readme.
The default sampling regions indeed refer to GRCh38,  and have been selected by hand by looking at different 1Mb regions far enough away from centromeres and telomeres  on each chromosome in UCSC and accepting them, if they did not contain any big flaws in the Umap M24 or Umap S24 tracks.
I quickly looked at the same regions in hg19 and i looks like the same intervals should work for it. 
So you can just copy the regions at the end of the readme ([section 10](https://github.com/kehrlab/PopDel#10---sampling-intervals-for-profile-parameter-estimation)), put it into a text-file, maybe adapt the chromosome names to fit your reference and give it to PopDel via the '-i' option.

**Comment by serosko** [comment]
Feature added in [v1.1.3](https://github.com/kehrlab/PopDel/releases/tag/v1.1.3).

**Comment by holtgrewe** [comment]
:tada:
