### ISSUE TITLE
Popdel not recognising cram file

### ISSUE THREAD

**Issue by melnel000** [kehrlab/PopDel#13]
Hi. I installed popdel via conda and tried to run it on a single cram file (aligned to hg38) using the popdel profile command. However, I am getting the following error message:

popdel profile - Profile creation from BAM-file
===============================================

[PopDel 2021-01-19 13:58:51] Command:  

/cbio/datasets/human/other-nmd/b38/FR07888912/cram/FR07888912.md.recal.cram 

./seqan/bam_io/bam_file.h:156 FAILED!  (BamFileIn: File format not specified.)

stack trace:
  0    [0x5607964d97cf]  popdel(+0x137cf)
  1    [0x56079653ee73]  popdel(+0x78e73)
  2    [0x56079654ec34]  popdel(+0x88c34)
  3    [0x5607964d22b5]  popdel(+0xc2b5)
  4    [0x7fb56b6ceb97]  __libc_start_main + 0xe7
  5    [0x5607964d2731]  popdel(+0xc731)

Aborted (core dumped)

Do you have any suggestions on how I can get the program to run?

Thanks,
Melissa

**Comment by serosko** [comment]
Hi Melissa,

which version of PopDel are you using?
You can get the version by just running PopDel without any parameters.

Sebastian

**Comment by melnel000** [comment]
Hi Sebastian

I am running PopDel version: 1.2.2

**Comment by serosko** [comment]
Ah, I see. CRAM file support was added in version 1.3.0, so 1.2.2 does only support BAM files.
You can try updating using
`
conda update popdel
`
If that does not give you version 1.3.0, it is because conda cannot resolve the dependencies for that version.
By adding the right conda channels and then installing/updating PopDel again, this should be resolved.
The process is described in the PopDel wiki:
[https://github.com/kehrlab/PopDel/wiki/01.-Dependencies#dependencies-for-installation-via-conda](https://github.com/kehrlab/PopDel/wiki/01.-Dependencies#dependencies-for-installation-via-conda)

Please let me know if this resolves your problem, or if I can do anything else to help.

**Comment by melnel000** [comment]
I already had those channels added:

(base) melnel000@slurm-login:/scratch3/users/melnel000/popdel/other_nmd$ conda config --add channels defaults
Warning: 'defaults' already in 'channels' list, moving to the top
(base) melnel000@slurm-login:/scratch3/users/melnel000/popdel/other_nmd$ conda config --add channels bioconda
Warning: 'bioconda' already in 'channels' list, moving to the top
(base) melnel000@slurm-login:/scratch3/users/melnel000/popdel/other_nmd$ conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(base) melnel000@slurm-login:/scratch3/users/melnel000/popdel/other_nmd$ conda install popdel
Collecting package metadata (current_repodata.json): done
Solving environment: done

All requested packages already installed.

Running conda update popdel downloaded some new packages but when I check the version again it remains v 1.2.2.

Do you have any other suggestions for me?

Thanks for the help,
Melissa

**Comment by serosko** [comment]
Can you try to uninstall PopDel using
`conda remove popdel`
and then to install the specific version with
`conda install popdel=1.3.0`?
If that does not work, I attached an environment file for conda.
[popdel1.3.0.env.zip](https://github.com/kehrlab/PopDel/files/5836129/popdel1.3.0.env.zip)
You just have to unpack it and then can use it to create a conda environment with all the dependencies using
`conda env create -f popdel1.3.0.env.yml`

**Comment by melnel000** [comment]
Thanks Sebastian, that fix seems to have worked. I now have popdel v1.3.0 installed. However, when I run the profile command, I now get a different error message:

popdel profile - Profile creation from BAM/CRAM file

[PopDel 2021-01-20 15:28:58] Command:  

/cbio/datasets/human/other-nmd/b38/FR07888912/cram/FR07888912.md.recal.cram 

[PopDel 2021-01-20 15:28:58] Found 1 read groups in input bam file '/cbio/datasets/human/other-nmd/b38/FR07888912/cram/FR07888912.md.recal.cram'.
[PopDel 2021-01-20 15:28:58] Reference consists of 3366 sequences with a total length of 3217346917 base pairs.
[PopDel 2021-01-20 15:28:58] Using default sampling intervals for GRCh38/hg38.
[PopDel 2021-01-20 15:28:59] Determined insert size histograms for all read groups using the interval(s): chr1:35000000-36000000
[PopDel 2021-01-20 15:28:59] Histogram statistics (median, mean, stddev) calculated.
[PopDel 2021-01-20 15:28:59] Finished parameter estimation.

Read group 'FR07888912.0':  SampledReadPairs=137221  Median=449  Mean=457.656  StdDev=104.557  AvgCoverage=41.1663  ReadLength=150

[PopDel 2021-01-20 15:28:59] Initialized window iterator with windowSize=256 and windowShift=256.
terminate called after throwing an instance of 'seqan::FileOpenError'
  what():  Could not open file *BAM/CRAM-FILE*.profile: iostream error
Aborted (core dumped)

**Comment by serosko** [comment]
That looks like a bug with the automatic determination of the output file name.
You should be able to circumvent it by specifying a name for your output file.
You can give it to PopDel using the '-o' parameter.
E.g `popdel profile mycramfile.cram -o myprofile.profile`

**Comment by serosko** [comment]
Fixed in release [v1.4.0](https://github.com/kehrlab/PopDel/releases/tag/v1.4.0).
