### ISSUE TITLE
SVLEN field does not conform to VCF standard

### ISSUE THREAD

**Issue by holtgrewe** [kehrlab/PopDel#14]
According to VCF 4.2 and 4.3:

![image](https://user-images.githubusercontent.com/521780/232750185-87a7d11a-d684-4faa-bdf9-03eee4d55d49.png)

[..]

![image](https://user-images.githubusercontent.com/521780/232750271-4eb0ff0e-37ac-494a-ad5a-881ea2c3d54c.png)

However, PopDel v1.1.3 writes out

```
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">
```

IOW: with `Number=1` rather than `Number=.`

**Comment by ro36** [comment]
Fixed
