### ISSUE TITLE
Adding INFO/SVMETHOD

### ISSUE THREAD

**Issue by holtgrewe** [kehrlab/PopDel#7]
Hi, what about adding an `INFO/SVMETHOD` tag similar to the way Delly adds it?

header

```
##INFO=<ID=SVMETHOD,Number=1,Type=String,Description="Type of approach used to detect SV">
```

record

```
SVMETHOD=POPDELv1.1.0
```

**Comment by serosko** [comment]
Hi,
this sounds like an easy addition. 
I will add this with the next version.

**Comment by serosko** [comment]
Feature added in release [v1.1.2](https://github.com/kehrlab/PopDel/releases/tag/v1.1.2)
