### ISSUE TITLE
Add INFO/END

### ISSUE THREAD

**Issue by holtgrewe** [kehrlab/PopDel#8]
This would make downstream's life much easier as it would allow `bcftools query -f "%CHROM\t%POS0\t%END\n" file.vcf.gz` for conversion to BED.

**Comment by serosko** [comment]
Thank you for your suggestion.
This will be introduced in the next version.

**Comment by serosko** [comment]
Feature added in realease [v1.1.2](https://github.com/kehrlab/PopDel/releases/tag/v1.1.2)
